project:
  type: website

website:
  title: ""
  navbar:
    background: light
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/sresthadatta-316541162
      - icon: github
        href: https://github.com/sresthadatta

format:
  html:
    theme: flatly
    css: styles.css
    toc: false